version: '3.5'

services:
  traefik:
    image: traefik:1.7 # The official Traefik docker image
    restart: always
    ports:
      - "80:80"     # The HTTP port
      - "443:443" # The Web UI (enabled by --api)
      - "8080:8080"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json

networks:
  web:
    external: true
