version: '3.5'

services:
  traefik:
    image: traefik:1.7
    restart: always
    ports:
      - "80:80"      # The HTTP port
      - "443:443"    # The HTTPS
      - "8080:8080"  # The Traefik Web UI
    networks:
      - web          # The network that docker containers will use for reverse proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json

networks:
  web:
    external: true   # Must be generated manually with 'docker network create web'    
